### ISSUE TITLE
'graphicui' is not defined

### ISSUE THREAD

**Issue by Pixie-zxie** [fabaindaiz/Spellsolver#3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'graphicui' is not defined

**Comment by fabaindaiz** [comment]
@Pixie-zxie Hello, at this moment I am working on generating documentation.  soon you will have information on how each part works.

**Comment by fabaindaiz** [comment]
I already added documentation on what each class and method does, soon i will add general documentation that explains the implementation of Spelsolver.

If you still have problems make sure you follow the instructions correctly and execute the files from the correct paths

**Comment by fabaindaiz** [comment]
I already added documentation on what each class and method does, soon i will add general documentation that explains the implementation of Spelsolver.

If you still have problems make sure you follow the instructions correctly and execute the files from the correct paths
