### ISSUE TITLE
add feature for adventure mode

### ISSUE THREAD

**Issue by Inokow** [fabaindaiz/Spellsolver#62]
can you add feature for adventure mode on blocking ice icon ?,, thankyou

**Comment by fabaindaiz** [comment]
Hello @Inokow, I have never played the spellcast adventure mode, can you describe what the blocking ice icon is so I can implement it?

**Comment by Inokow** [comment]
hallo, 

asdfs
poqwe
as[d]lk
aziop
sdjqw

let's say [d] is an ice icon and the place is random, sometimes it can be 2 to 5, not just 1. The ice icon is a letter that cannot be arranged as a sentence.
So when I press 0swaps the ice icon should not be listed as a letter.
so all 25 letters only read 20 to 24 letters.
Thank You

**Comment by fabaindaiz** [comment]
Hello @Inokow, a basic blocking ice icon functionality was added.
If you find any bugs or incorrect behavior, please let me know.

**Comment by Inokow** [comment]
thanks sir
its work perfectly
