### ISSUE TITLE
Multiple bonus and freemove with arrow keys

### ISSUE THREAD

**Issue by Dovcrowc** [fabaindaiz/Spellsolver#64]
hai

1. can you add some free move and replace because i sometime miss typing.
2. and can you add some extra multiple DL and TL like a Gems function, because in adventure mode, sometime have 3TL / DL . maybe some multiple 2X too ?? 
 
tenkyu

**Comment by fabaindaiz** [comment]
Hello @Dovcrowc,
I am considering adding an adventure mode to the software with these extra features in the next few weeks.

**Comment by fabaindaiz** [comment]
Hello @Dovcrowc,
The requested new features were added along with the latest release
