### ISSUE TITLE
Can't execute graphicui.py

### ISSUE THREAD

**Issue by Kyusune** [fabaindaiz/Spellsolver#8]
I'm trying to execute the graphicui.py option but I am running into crashes.
Here is the error that I have
![image](https://github.com/fabaindaiz/Spellsolver/assets/98139618/db232607-bfe2-4bc5-b8fe-8e284a23cd67)

**Comment by fabaindaiz** [comment]
@Kyusune there was a bad import, corrected with the last pull request

**Comment by Kyusune** [comment]
Thanks it works now!
